---
- hosts: all
  tasks:
    - shell: "wget -O - https://www.ticketscale.io/ticketscale.gpg.key|apt-key add -"
    - apt_repository: repo='deb [arch=amd64] http://public-debs.ticketscale.io/ticketscale-public/ trusty main' state=present
    - name: Install list of packages
      apt: name={{item}} state=installed update_cache=yes
      with_items:
           - htop
           - libzookeeper-mt2
           - libpcre3-dev
           - libboost-program-options-dev
           - libprotobuf-dev
           - libboost-system-dev

    - apt: name=ramcloud update_cache=yes

    - file: path=/opt/ramcloud/obj/server owner=root group=root mode=0755

    - apt_repository: repo=ppa:ubuntu-toolchain-r/test

    - apt: name=g++-4.9 update_cache=yes state=installed

    - shell: "nohup /opt/ramcloud/obj/server --clusterName testcluster -x zk:zookeeper1:2181,zookeeper2:2181,zookeeper3:2181 --totalMasterMemory 3072 -r 2 &> nohup2.out &"